### PR TITLE
Improve quick-start docs: remove redundant doc for setting up local env, add env set-up guide on readme, and add notes for customized setup

### PR DESCRIPTION
**Pull request by yuey002**
Since we already have the documentation to set up a local k8s cluster with Godel, remove this dev-quickstart-guide readme instead of maintaining two docs with the same purpose. Added the environment setup guide link on the README page.

Also, improved the quick-start guides with notes for customized setups.

### CODE REVIEW

**Comment by NickrenREN** [comment]
can we put the installation guide in README file instead of  each feature doc  ?

**Comment by lintongj** [comment]
> can we put the installation guide in README file instead of each feature doc ?

It might be a little bit distracting as the installation guide is pretty long. How about add a link to this page in the README?

**Comment by NickrenREN** [comment]
> How about add a link to this page in the README?

That is exactly what i want

**Comment by yuey002** [comment]
@NickrenREN @lintongj Please review again when getting a chance. Besides adding the cluster set-up link on README, I also made two other changes in this PR
1) Separate the kind config files for job-level-affinity and concurrent scheduling, since they require extra lables on node;
2) Add notes for worker node capacity (which depends on the user's local docker resource config).

I have tested the workflows for all quick-starts (gang, preemption, etc)

**Review by lintongj — APPROVED** [review]

**Comment by NickrenREN** [comment]
@yuey002 thanks， merging

**Pull request merged**
